#!/usr/bin/env bash
# Bulk copy stuff to mac
# Use this when you gotta go on a flight or something, then can just copy data over
# globs=('/mdata1/ldavis/*troprad2*t42l20s*' '/mdata1/ldavis/*tgrad*t42l20s*')
#------------------------------------------------------------------------------#
# For copying raw data:
# prefix=/mdata1/ldavis # for scratch, or
# suffix=netcdf
#------------------------------------------------------------------------------#
# For copying processed data:
prefix=/home/ldavis/data
suffix=
#------------------------------------------------------------------------------#
# Function to copy stuff
function rlcp() { # "copy to local (from remote); 'copy there'"
  local port file dest
  # port=$(cat ~/.port)
  port=10000 # manual
  array=${@:1:$#-1}
  dest=${!#}
  echo "(Port $port) Copying ${array[@]} on this server to home server at: $dest..."
  command scp -o StrictHostKeyChecking=no -P$port ${array[@]} ${USER}@localhost:"$dest"
}
#------------------------------------------------------------------------------#
# Copy the stuff
# shopt -s nullglob
folders=() # store all files to be copied
# globs=('*tgrad*t42l20s*' '*troprad2*t42l20s*')
# globs=('*troprad3*t42l20s*')
# globs=('*troprad[23]*t42l40s*' '*stratrad1c*t42l50p*' '*stratrad10c*t42l50p*' '*base*t42*')
globs=('*troprad3*t42l20s*')
for pattern in ${globs[@]}; do
  for dir in $prefix/$pattern; do
    dir=$dir/$suffix
    folders+=(${dir%/})
  done
done
rlcp -r ${folders[@]} /Users/ldavis/data
