#!/usr/bin/env bash
#------------------------------------------------------------------------------#
# Standardize attributes
# Now these lines are in the NCL interp script, because needed to access it from
# different places, didn't want to have to copy paste every time
#------------------------------------------------------------------------------#
# Many of these may already be properly set, but make sure; CDO also may want
# a few special ones like 'axis' and 'standard_name'
# NOTE: This is really fast (0.02s on T42 20 day file)
# This is much faster than even editing one attribute in NCL (0.05s)
# NOTE: We set the calendar to '360_day' because that seems reasonable for
# an equinoctial model run (even months of 30), and software like CDO and
# xarray cannot interpret the default 'NO_CALENDAR'
ncatted -O -h \
  -a edges,lon,d,, -a edges,lat,d,, \
  -a axis,lon,o,c,"X" -a axis,lat,o,c,"Y" -a axis,plev,o,c,"Z" -a axis,time,o,c,"T" \
  -a long_name,plev,o,c,"pressure level" -a units,plev,o,c,"mb" -a bounds,plev,o,c,"plev_bnds" \
  -a long_name,lat,o,c,"latitude"  -a standard_name,lat,o,c,"latitude" \
  -a long_name,lon,o,c,"longitude" -a standard_name,lon,o,c,"longitude" \
  -a calendar_type,time,d,, -a calendar,time,o,c,"360_day" -a standard_name,time,o,c,"time" \
  -a units,lat,o,c,"degrees north" -a units,lon,o,c,"degrees east" $output
