#!/usr/bin/env bash
# NOTE: This file adds simple stuff that can just be calculated
# from the summary file alone!
# Iterate through a bunch of glob patterns
# in the scratch directory
# shopt -s nullglob
repair=./add_summary.ncl
nclcheck() {
  cat $1 | grep -v "Execute.c" | grep -v "systemfunc" | egrep "^fatal:" &>/dev/null
  return $? # is *zero* if we *found error strings*
}
case ${HOSTNAME%%.*} in
  monde)
    scratch=/mdata1/ldavis
  ;; cheyenne*)
    scratch=/glade/scratch/davislu # https://www2.cisl.ucar.edu/resources/storage-and-file-systems/glade-file-spaces
  ;; *) echo "Error: Unknown host, must edit batch script before continuing." && exit 1 ;;
esac
# Loop
globs=('hs_troprad3_t95l60e*1000*' 'hs_tgrad_t95l60e*')
for glob in "${globs[@]}"; do
  for dir in $scratch/$glob; do
    echo "Dir: ${dir##*/}"
    filenames=($dir/netcdf/*summary.d????-d????.nc)
    for filename in ${filenames[@]}; do
      echo "File: ${filename##*/}"
      # output=${filename%.nc}_tmp.nc # try again
      # [ -r $output ] && rm $output
      ncl -n -Q "filename=\"$filename\"" $repair 2>&1 | tee log.fix #2> /dev/null
      nclcheck log.fix
      [ $? -eq 0 ] && echo "Error: Failed." && exit 1
    done
  done
done
