#!/bin/bash
# Script for compiling fortran source code, as user has specified. Then the runscript will integrate
# it forward, produce output, etc.
#------------------------------------------------------------------------------
# Fix host-specific settings
#------------------------------------------------------------------------------
expname=pk
hostname=${HOSTNAME%%.*} # trims e.g. monde.atmos.colostate.edu
case ${HOSTNAME%%.*} in
  olbers) # netcdf-c lib is separate from netcdf-fortran lib
    include=(/usr/local/mpich3/include /usr/local/netcdf4/include /usr/local/netcdf4-pgi/include)
    links=(/usr/local/mpich3/lib /usr/local/netcdf4/lib /usr/local/netcdf4-pgi/lib /usr/local/hdf5/lib)
    root=/home/ldavis/gfdl
    pgi=/opt/pgi/linux86-64/2017/bin
    # fix=' -lcurl' # not sure why needed this, probably fake news
    ;;
  gauss) # libs are together; slightly different naming (not sure why mpich and hdf5 have
         # 'pgi' and 'gcc' options, should be copies; only netcdf-fortran can be compiled with either)
    include=(/usr/local/mpich3-pgi /usr/local/netcdf4-pgi/include)
    links=(/usr/local/mpich3-pgi/lib /usr/local/netcdf4-pgi /usr/local/hdf5-pgi/lib)
    root=/home/ldavis/gfdl
    pgi=/opt/pgi/linux86-64/2016/bin
    # fix=' -lcurl'
    ;;
  monde)
    include=(/usr/include/mpich-x86_64)
    links=(/usr/lib64/mpich/lib)
    root=/home/ldavis/gfdl
    pgi=/opt/pgi/linux86-64/17.10/bin
    # fix=' -lcurl'
    ;;
  euclid) # everything is bunched together
    include=(/usr/local/include)
    links=(/usr/local/lib)
    root=/birner-home/ldavis/gfdl
    pgi=/opt/pgi/linux86-64/2013/bin
    # fix=''
    ;;
  *) echo "Error: Unknown host, must configure library and binary locations before running." && exit 1 ;;
esac
#------------------------------------------------------------------------------
# Build executable model code and post-processing tool
#------------------------------------------------------------------------------
# Definitions
execdir=${expname}_${HOSTNAME%%.*}      # where code is compiled and executable is created
src=$root/src                                  # path to directory containing model source code
mkmf=$root/bin/mkmf                            # path to executable mkmf
mkmftemplate=$root/bin/mkmf.template           # template of most basic settings
mppnsource=$root/postprocessing/mppnccombine.c # source code
pathnames=$src/path_names_$expname             # stored in source directory
cppdefs="-Duse_libMPI -Duse_netCDF"            # not sure what this does
flags_links="${links[@]/#/-L}"                 # search these paths for library files
flags_include="${include[@]/#/-I}"             # include flags
flags_libs="-lmpl -lmpich -lfmpich -lmpichf90 -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm -lz $fix" # for mppnccombine
# Make sure necessary things tools are in path
[ ! -d $execdir ]      && mkdir $execdir || echo "Warning: Leaving old compiled source."
[ ! -d $src ]          && echo "Error: Could not find source code directory $src."        && exit 1
[ ! -r $pathnames ]    && echo "Error: Could not find path_names file $pathnames."        && exit 1
[ ! -r $mppnsource ]   && echo "Error: Could not find mppnccombine source code."          && exit 1
[ ! -r $mkmftemplate ] && echo "Error: Could not find mppnccombine source code."          && exit 1
[ ! -r $mkmf ]         && echo "Error: Could not find Makefile-generating utility $mkmf." && exit 1
#------------------------------------------------------------------------------#
# Create mppnccombine; should supply with same libraries supplied to model executable through its makefile
# $pgi/pgcc -O -o $mppnccombine -I$netcdfc/include -I$mpich/include $mppnsource $flags_links $flags_libs
time=$(date +%s)
echo "Generating mppnccombine executable..."
$pgi/pgcc -O -o mppnccombine.x $flags_include $mppnsource $flags_links $flags_libs
  # -O[level] = set optimization level; sets to 2 if number not specified
  # -o file = use this file as name of executable
  # -Idirectory = add directory to compiler search path; these are 'header' files
  # -Ldirectory = change the directory in which "linker" searches for libraries
  # -llibrary = load lib<library>.a from the standard library directory (supplied by L?)
  # ...the mpllibs in MPICH seem to only have .so instead of .a ... not sure what that means
  # ...also it seems there is no libm.a or libz.a
#------------------------------------------------------------------------------#
# Build makefile template (assumes pgi bin is on $PATH)
cd $execdir # move to source directory
cat > mkmf.template << DELIM
CC = $pgi/pgcc
FC = $pgi/pgf90
LD = $pgi/pgf90
CPPFLAGS = -Mmpi=mpich
FFLAGS = -Mmpi=mpich -r8 -Ktrap=fp -pc 64 -O2
LDFLAGS = $flags_links $flags_libs -Mmpi=mpich
LIST = -Mlist
DELIM
cat $mkmftemplate >> mkmf.template # appends provided template to custom defs
#------------------------------------------------------------------------------#
# Create makefile
echo "Generating Makefile..."
cat mkmf.template
$mkmf -p fms.x -t mkmf.template -c "$cppdefs" -a $src $pathnames \
  $src/shared/mpp/include $src/shared/include ${include[@]} # the other include files
  # -p = program (name of final target)
  # -t = template (list of MACROS/COMMANDS that get appended to beginning of final Makefile)
  # -c = list of 'cpp #define's passed to source files (what?)
  # -a = abspath, attaches 'abspath' (here, $src) to the FRONT of RELATIVE paths to the source file
  # args (all the later stuff) = list of directories/files to be searched for targets and dependencies
#------------------------------------------------------------------------------#
# Compile source
echo "Compiling source code..."
make -f Makefile
echo "This script took $(($(date +%s) - $time)) seconds."

