#!/usr/bin/env bash
shopt -s nullglob
#------------------------------------------------------------------------------#
# Show files currently available
#------------------------------------------------------------------------------#
log=${0}.log
root=~/data/timescales
prefix=2xdaily
rm $log 2>/dev/null
globs=("*t42l20s*" "*t42l10s*")
for glob in "${globs[@]}"; do
  for folder in $root/$glob; do
    # Get params corresponding to that parameter series
    dir=${folder##*/}
    nfields=$(echo $dir | tr '[^_]' ' ' | wc -w)
    iseries=${dir%_p*}
    [ "$iseries" != "$series" ] && printf "\nSeries: $iseries\n" | tee -a $log # new line
    series=$iseries
    if [ $nfields -eq 3 ]; then
      params="default"
    else
      params=${dir##*_}
      params="$(echo $params | tr p ' ' | sed 's/ 0*/ /g' | sed 's/ \./ 0./g' | xargs | sed 's/ /, /g')"
    fi
    echo $params | tee -a $log # parameters
    # Print if file available
    unset message
    for file in forcing climate climate_isen spectral spectral_phase eofs_nh eofs_nh_vert energy; do
      if [ $file == forcing ]; then
        ncfile=($folder/*${file}.nc)
      else
        ncfile=($folder/${prefix}*${file}.nc)
      fi
      if [ ${#ncfile[@]} -ne 0 ]; then
        message+="$file: $(date -u -r $ncfile)\n"
      fi
    done
    printf "$message" | column -t -o' ' | awk '{print "    " $0}' | tee -a $log
  done
done
