#!/usr/bin/env bash
# List the NetCDF files stored in every single
# experiment directory.
shopt -s nullglob
names=($@) # remember $@ is special, nothing gets expanded
[ -z "$1" ] && names=("hs*")
case $HOSTNAME in
  monde*)    roots=(~/mdata2 ~/mdata1)                            ;;
  cheyenne*) roots=(~/scratch)                                    ;;
  *)         echo "Error: Unknown host ${HOSTNAME}." && exit 1 ;;
esac
# Ncvarlist
nclist() {
  command ncdump -h "$1" | sed -n '/variables:/,$p' | sed '/^$/q' | grep -v '[:=]' \
    | cut -d';' -f1 | cut -d'(' -f1 | sed 's/ *$//g;s/.* //g' | xargs | tr ' ' '\n' | grep -v '[{}]' | xargs
}
ncdimlist() {
  command ncdump -h "$1" | sed -n '/dimensions:/,$p' | sed '/variables:/q' \
    | cut -d'=' -f1 -s | xargs | tr ' ' '\n' | grep -v '[{}]' | xargs
}
ncvarlist() {
  local list dmnlist varlist
  list=($(nclist "$1"))
  dmnlist=($(ncdimlist "$1"))
  for item in "${list[@]}"; do
    if [[ ! " ${dmnlist[@]} " =~ " $item " ]]; then
      varlist+=("$item")
    fi
  done
  echo "${varlist[@]}" | tr -s ' ' '\n' | grep -v '[{}]' | sort | xargs | sed 's/plev_bnds //'
}

# Iterate
echo
prefix=2xdaily_inst
log=${0}.log
eday=5400 # last starting day for runs
series=''
rm $log 2>/dev/null
for root in ${roots[@]}; do
  echo "Root: $root" | tee -a $log
  unset globs
  for name in "${names[@]}"; do
    globs+=($root/$name) # performs expansion
  done
  [ ${#globs[@]} -eq 0 ] && echo "No $name files found in ${root}." && continue
  for path in ${globs[@]}; do
    # Get params corresponding to that parameter series, so
    # we can echo them
    dir=${path##*/}
    nfields=$(echo $dir | tr '[^_]' ' ' | wc -w)
    iseries=${dir%_p*}
    [ "$iseries" != "$series" ] && printf "\nSeries: $iseries\n" | tee -a $log # new line
    series=$iseries
    if [ $nfields -eq 3 ]; then
      params="default"
    else
      params=${dir##*_}
      params="$(echo $params | tr p ' ' | sed 's/ 0*/ /g' | sed 's/ \./ 0./g' | xargs | sed 's/ /, /g')"
    fi
    echo $params | tee -a $log # parameters

    # Loop through summary files
    unset day1 day2 vars1 vars2
    for file in $path/netcdf/${prefix}_summary.d????-d????.nc; do
      # Get day
      day2="${file#*_summary.d}"
      day2="${day2%-*}"
      vars2="$(ncvarlist $file)"
      if [ -z "$day1" ]; then # initialize
        day1=$day2
        vars1=$vars2
      elif [ $eday == $day2 ] || [ "$vars1" != "$vars2" ]; then
        echo "  ${day1}-${day2}: $vars1" | tee -a $log
        day1=$day2
        vars1=$vars2
      fi
    done
  done
  echo | tee -a $log
done
