#!/usr/bin/env bash
# List the NetCDF files stored in every single
# experiment directory.
shopt -s nullglob
names=($@) # remember $@ is special, nothing gets expanded
[ -z "$1" ] && names=("hs*")
case $HOSTNAME in
  monde*)    roots=(~/mdata1 ~/mdata2)                            ;;
  cheyenne*) roots=(~/scratch)                                    ;;
  *)         echo "Error: Unknown host ${HOSTNAME}." && exit 1 ;;
esac
# Print days
day_range() {
  local files ns nd
  files=($@)
  files=(${files[@]%.nc}) # from dir/dir/stuff.dXXXX-dYYYY.nc to dir/dir/stuff.dXXXX-dYYYY
  files=(${files[@]##*.}) # from dir/dir/stuff.dXXXX-dYYYY to dXXXX-dYYYY
  if [ ${#files[@]} -eq 0 ]; then
    echo 0 0
  else
    ns=${files[0]:1} # from dXXXX-dYYYY to XXXX-dYYYY
    ns=$(printf "%.0f" ${ns%-*}) # from XXXX-dYYYY to XXXX
    nd=${files[-1]}
    nd=$(printf "%.0f" ${nd##*d}) # from dXXXX-dYYYY to YYYY
    echo $ns $nd
  fi
}

# Iterate
echo
cwd=$(pwd)
unset series
prefix=2xdaily_inst # then there are _full, _summary, _summary_isen, _full_isen, and _spectral
log=$cwd/${0##*log_}.log
echo $log
eday=5500
rm $log 2>/dev/null
for root in ${roots[@]}; do
  unset globs
  # echo "Root: $root" | tee -a $log
  echo "Root: $root" &>> $log
  for name in "${names[@]}"; do
    globs+=($root/$name) # performs expansion
  done
  [ ${#globs[@]} -eq 0 ] && echo "No $name files found in ${root}." && continue
  for dir in ${globs[@]}; do
    # Get timestep
    cd -P $dir
    if [ -r input.nml ]; then
      dt=$(cat input.nml | grep dt_atmos | cut -d= -f2 | cut -d, -f1 | xargs)
    else
      dt='???'
    fi
    # Get day range for folders
    unset message
    dd=($(day_range d????-d????))
    for suffix in full summary full_isen summary_isen spectral; do
      fd=($(day_range netcdf/${prefix}_${suffix}.d????-d????.nc))
      if [ ${fd[1]} -gt 0 ]; then
        message+=", ${suffix}: ${fd[0]}-${fd[1]}"
      fi
    done
    if ! [ -r forcing.nc ]; then
      message+=", no forcing.nc"
    fi
    message="${message:2}"
    # Get params corresponding to that parameter series
    dir=${dir##*/}
    nfields=$(echo $dir | tr '[^_]' ' ' | wc -w)
    iseries=${dir%_p*}
    # [ "$iseries" != "$series" ] && printf "\nSeries: $iseries\n" | tee -a $log # new line
    [ "$iseries" != "$series" ] && printf "\nSeries: $iseries\n" &>> $log # new line
    series=$iseries
    if [ $nfields -eq 3 ]; then
      params="default"
    else
      params=${dir##*_}
      params="$(echo $params | tr p ' ' | sed 's/ 0*/ /g' | sed 's/ \./ 0./g' | xargs | sed 's/ /, /g')"
    fi
    # echo $params | tee -a $log # parameters
    # echo "    dt: ${dt}, last day: ${dd[1]}." | tee -a $log
    # echo "    $message" | tee -a $log
    echo $params &>> $log # parameters
    echo "    dt: ${dt}, last day: ${dd[1]}." &>> $log
    echo "    $message" &>> $log
  done
  echo &>> $log
done
