#!/usr/bin/env bash
################################################################################
# Use this file to document the commands used to post-process various experiment
# series with the 'post_series' script, or generate derivative data from full
# resolution archived data with 'process_post'.
################################################################################
# Calculate spectral data
if false; then
  ./process_post -p=8 -s \
    'hs_base[12]_*' 'hs_tgrad[12]_*' 'hs_tdamp[12]-mean_*' 'hs_tdamp[12]_*'
  exit $?
fi
# Basic runs
# ./post_series -p=4 'hs_base[12]_*' 'hs_tmean[12]_*' 'hs_tgrad[12]_*' 'hs_tdamp[12]-mean_*' 'hs_tdamp[12]_*' \
#   -c1=500 -c2=3500 -cc -cci -cce
# ./post_series 'hs_base[12]_*' 'hs_tmean[12]_*' 'hs_tgrad[12]_*' 'hs_tdamp[12]-mean_*' 'hs_tdamp[12]_*'\
#   -c1=500 -c2=1500 -eof -auto
# ./post_series 'hs_tdamp[12]-mean_*' 'hs_tdamp[12]_*' \
#   -c1=500 -c2=1500 -auto

# Forcing experiments and bases, or locked runs
# for flags in '-f' '-p=1 -cp' '-p=1 -cce' '-p=1 -ci' '-p=4 -cv -ca'; do
# for flags in '-p=4 -cp' '-p=4 -ci' '-p=4 -ce' '-p=4 -cv'; do
# for flags in '-p=4 -ce' '-p=4 -cv'; do
# for flags in '-f' '-p=4 -cv'; do
# for flags in '-f' '-p=4 -cp'; do
# for flags in '-f' '-p=4 -cv'; do
# for flags in '-f' '-p=4 -cp'; do
lock=''
# lock='[LC]'
blopt='[12]'
for flags in '-p=4 -ce'; do
  echo "Flags: $flags"
  # "hs_tdamp${blopt}-arctic*" "hs_tdamp${blopt}-vortex*" "hs_tdamp${blopt}-tropical*" \
  # "hs_tdamp${blopt}-global*" "hs_tdamp${blopt}-surface*" \
  ./post_series \
    "hs${blopt}${lock}_base_*" "hs${blopt}${lock}_tdamp_*" \
    "hs${blopt}${lock}_tdampmean_*" \
    "hs${blopt}${lock}_tgrad_*" \
    "hs${blopt}${lock}_tmean_*" \
    -c1=0 -c2=3500 $flags
done

# Diagonal experiments and diagonal experiment base
# for flags in '-p=4 -cp' '-p=4 -ci' '-p=4 -ce' '-p=4 -cv'; do
# for flags in '-f' '-p=4 -cv'; do
# for flags in '-f' '-p=4 -cv'; do
#   echo "Flags: $flags"
#   ./post_series \
#     "hs_tmean_*" "hs_tgrad_*" \
#     -c1=500 -c2=3500 $flags
#     # "hs_tdamp-tmean*" "hs_tdamp-tgrad*" \
# done
