#!/usr/bin/env bash
#-----------------------------------------------------------------------------#
# Use this file to document the commands used to post-process various experiment
# groups with the 'post_glob' script, or generate derivative data from full
# resolution archived data with 'process_post'.
#-----------------------------------------------------------------------------#
shopt -s nullglob

# Forcing experiments and bases, or locked runs
# NOTE: The control experiments have drift problem so ignore
# blopt='[12]'
# for tstart in 500 750 1000 1250 1500; do
# for tstart in 500 1000 1500; do
for flags in -cp -ci -ts -te; do
  for tstart in 500; do
    for tend in 7000 7500; do
    # for tend in 5500 6000 6500 7000 7500; do
    # for tend in 5500 6000 6500; do
    # for tend in 5500 3500; do
      # for blopt in 1; do
      for blopt in 1; do
        # for reso in t42l20s; do
        # for reso in t85l60e t42l20s; do
        for reso in t85l60e; do
          # for flags in '-c -ca'; do
          # for flags in -c -cp -ci -ts -te; do
          echo "Flags: $flags"
          ./post_sweep \
            "hs${blopt}_${reso}_ntau????.???" \
            "hs${blopt}_${reso}_ntau????.???c" \
            "hs${blopt}_${reso}_ntau????.???_qrealistic*" \
            "hs${blopt}_${reso}_ntau????.???c_qrealistic*" \
            -r=20 -c1=$tstart -c2=$tend $flags
            # "hs${blopt}_${reso}*" \
            # "hs${blopt}?${reso}" \
            # "hs${blopt}_${reso}_tgrad????.???" \
            # "hs${blopt}_${reso}_tgrad????.???c" \
            # -r=20 -c1=500 -c2=$tend $flags
            # -r=100 -c1=500 -c2=5500 $flags
        done
      done
    done
  done
done

# Calculate spectral data, *deleting* data as we go
# NOTE: Ensure home directory has symlink to scratch on every server
# NOTE: Critical that we proceed one experiment at a time or the disk fills up
# for dir in ~/scratch1/hs[12]*{base,ntau,ntaumean,tgrad}*; do
#   # data=(~/data/timescales/$glob/2xdaily_inst_spectral*.*.nc)  # spectral and 'phase' data
#   # [ "${#data[@]}" -eq 2 ] && { echo "Skipping: $glob"; continue; }
#   glob="${dir##*/}"
#   echo
#   echo "Spectral blocks: $glob"
#   ./process_after -s -n=8 "$glob" && {
#     echo
#     echo "Spectral average: $glob"
#     ./post_glob -o -cs -c1=500 -c2=5500 "$glob"
#   }
# done
