#!/bin/bash
# Really a BASH script; this runs CDO commands on the file.
################################################################################
# Helper functions: see http://nco.sourceforge.net/nco.html#index-ncdmnlist
# function ncgrplist() { ncks -m $1 | grep -v '[:=]' | cut -d ';' -f 1 -s | tr -s ' ' | cut -d ' ' -f 2; }
# function ncdmnlist() { ncks -m $1 | cut -d ':' -f 1 | cut -d '=' -s -f 1 | xargs; }
# function ncvardump() { ncks -s "%f " -H -C -v $1 $2; }
function ncvarlist() { ncks -m $1 | grep -v '[:=]' | cut -d '(' -f 1 -s | sed 's/.* //g' | xargs; }
  # cut tabulates data; -d chooses delimiter, -f chooses field (1 is first column, 2 is second, etc.)
  # and lines with no delimiters present always printed unless -s is selected; grep -v is inverse of
  # selection (so only blank lines/variable header titles remain) and the sed command leaves only trailing
  # non-whitespace character (so trims leading tab and 'float', 'double', etc. identifiers)
################################################################################
# Processing data with CDO: main function
# Adds flux terms, variance terms and consolidates them into a file
# * Have issue with "enlarge" command when variables exist with more than one 
#   possible vertical coordinate (bhalf); need to remove them; or just don't output bhalf
# * So we delegate to NCO and NCL the job of fixing coordinates.
t=$(date +%s)
echo "Saving parameters with CDO..."
ncfile=$1 # take single file as argument
outfile=$2 # output file
flags="-s -O" # need -O because sometimes get prompted to overwrite
timmean="" # for now not implemented
delnames="" # no longer writing vorticity; get after-fact with cdo uv2dv
# delnames=vor # not meaningful in longitude-mean
#   # vor was only kept as an interesting parameter to visualize
##############################################################################
# First get the basic zonal mean of everything
cdo $flags -zonmean $timmean -delname,$delnames $ncfile out1.nc #2>/dev/null
echo "  * Time for basic zonal mean: $(($(date +%s) - $t))s."
  # keep zonal-means of everything else, because interesting
# If we do not have instantaneous data don't bother with some stuff
[[ " $(ncvarlist $ncfile) " =~ " time_bounds " ]] && { mv out1.nc $outfile; return; }
##############################################################################
# Heat flux and momentum flux
t=$(date +%s)
out=out2.nc
cdo $flags chname,t,EHF -zonmean $timmean \
  -mul -sub -selvar,t $ncfile -enlarge,$ncfile -zonmean -selvar,t $ncfile \
       -sub -selvar,v $ncfile -enlarge,$ncfile -zonmean -selvar,v $ncfile \
  $out #2> /dev/null # heat flux, with EP scaling
ncatted -O -a long_name,EHF,m,c,"eddy heat flux" $out 2>/dev/null
ncatted -O -a units,EHF,m,c,"K m/s" $out 2>/dev/null
echo "  * Time for eddy heat flux: $(($(date +%s) - $t))s."
t=$(date +%s)
out=out3.nc
cdo $flags chname,u,EMF -zonmean $timmean \
  -mul -sub -selvar,u $ncfile -enlarge,$ncfile -zonmean -selvar,u $ncfile \
       -sub -selvar,v $ncfile -enlarge,$ncfile -zonmean -selvar,v $ncfile \
  $out #2> /dev/null # momentum flux, needs no EP scaling
ncatted -O -a long_name,EMF,m,c,"eddy momentum flux" $out 2>/dev/null
ncatted -O -a units,EMF,m,c,"m2/s2" $out 2>/dev/null
echo "  * Time for eddy momentum flux: $(($(date +%s) - $t))s."
t=$(date +%s)
out=out4.nc
cdo $flags chname,t,VHF -zonmean $timmean \
  -mul -sub -selvar,t $ncfile -enlarge,$ncfile -zonmean -selvar,t $ncfile \
       -sub -selvar,omega $ncfile -enlarge,$ncfile -zonmean -selvar,omega $ncfile \
  $out #2> /dev/null # vertical heat flux
ncatted -O -a long_name,VHF,m,c,"vertical heat flux" $out 2>/dev/null
ncatted -O -a units,VHF,m,c,"W/m2" $out 2>/dev/null
echo "  * Time for vertical heat flux: $(($(date +%s) - $t))s."
# Omit PV because it is only really relevant on theta-surfaces
# cdo $flags chname,pv,EPF -zonmean $timmean \
#   -mul -sub -selvar,pv $ncfile -enlarge,$ncfile -zonmean -selvar,pv $ncfile \
#        -sub -selvar,v $ncfile -enlarge,$ncfile -zonmean -selvar,v $ncfile \
#   out4.nc #2> /dev/null # PV flux
# ncatted -O -a long_name,EPF,m,c,"eddy PV flux" out4.nc 2>/dev/null
# ncatted -O -a units,EPF,m,c,"K m3/kg s2" out4.nc 2>/dev/null
# echo "  * Time for eddy PV flux: $(($(date +%s) - $t))s."
##############################################################################
# Energy terms EKE each latitude and KE generation each latitude
# * EKE and KE should be multiplied by level width dP; final units are J/m2
# * CKE should be multiplied by level width over pressure dP/P; units don't change
t=$(date +%s)
out=out5.nc
cdo $flags chname,u,EKE $timmean -divc,9.81 -divc,2 \
  -add -zonmean -sqr -sub -selvar,u $ncfile -enlarge,$ncfile -zonmean -selvar,u $ncfile \
       -zonmean -sqr -sub -selvar,v $ncfile -enlarge,$ncfile -zonmean -selvar,v $ncfile \
  $out #2> /dev/null # eddy kinetic energy
echo "  * Time for EKE: $(($(date +%s) - $t))s."
ncatted -O -a long_name,EKE,m,c,"eddy kinetic energy" $out 2>/dev/null
ncatted -O -a units,EKE,m,c,"J/m2 Pa" $out 2>/dev/null
t=$(date +%s)
# This aint right
# cdo $flags chname,t,CKE $timmean -divc,9.81 -mulc,287 \
#   -zonmean -mul -sub -selvar,t $ncfile -enlarge,$ncfile -zonmean -selvar,t $ncfile \
#                 -sub -selvar,omega $ncfile -enlarge,$ncfile -zonmean -selvar,omega $ncfile \
#   $out #2> /dev/null # vertical heat flux
# ncatted -O -a long_name,CKE,m,c,"kinetic energy generation" $out 2>/dev/null
# ncatted -O -a units,CKE,m,c,"W/m2" $out 2>/dev/null
# echo "  * Time for KE generation term: $(($(date +%s) - $t))s."
# Omit total KE because it can be calculated on-the-fly very easily
# t=$(date +%s)
# cdo $flags chname,u,KE $timmean -divc,9.81 -divc,2 \
#   -add -zonmean -sqr -selvar,u $ncfile \
#        -zonmean -sqr -selvar,v $ncfile \
#   out7.nc #2> /dev/null # total kinetic energy
# ncatted -O -a long_name,KE,m,c,"total kinetic energy" out7.nc 2>/dev/null
# ncatted -O -a units,KE,m,c,"J/m2 Pa" out7.nc 2>/dev/null
# echo "  * Time for total KE term: $(($(date +%s) - $t))s."
##############################################################################
# Simple terms: zonal eddy-u variance, eddy-T variance
# These are from Held-Suarez ideas
t=$(date +%s)
out=out6.nc
cdo $flags chname,t,tvar -zonmean $timmean \
  -sqr -sub -selvar,t $ncfile -enlarge,$ncfile -zonmean -selvar,t $ncfile \
  $out #2> /dev/null # heat flux, with EP scaling
ncatted -O -a long_name,tvar,m,c,"temperature eddy-variance" $out 2>/dev/null
ncatted -O -a units,tvar,m,c,"K2" $out 2>/dev/null
echo "  * Time for temperature variance: $(($(date +%s) - $t))s."
t=$(date +%s)
out=out7.nc
cdo $flags chname,u,uvar -zonmean $timmean \
  -sqr -sub -selvar,u $ncfile -enlarge,$ncfile -zonmean -selvar,u $ncfile \
  $out #2> /dev/null # heat flux, with EP scaling
ncatted -O -a long_name,uvar,m,c,"zonal-wind eddy-variance" $out 2>/dev/null
ncatted -O -a units,uvar,m,c,"m2/s2" $out 2>/dev/null
echo "  * Time for zonal wind variance: $(($(date +%s) - $t))s."
# TODO: zonal spectra? could store these for just a couple parameters,
# and truncate at lower wavenumbers
##############################################################################
# Combine, and check previous output
t=$(date +%s)
echo "Combining all CDO output."
files=(out{1..7}.nc) # uses brace expansion, captures expansion in array
for file in ${files[@]}; do
  [ ! -r $file ] && { echo "ERROR: File $file not found."; exit 3; } # will exit shell, not function
    # see: https://stackoverflow.com/q/4419952/4970632
done
cdo $flags merge ${files[@]} $outfile #2> /dev/null
echo "  * Time for merging result: $(($(date +%s) - $t))s."

