#!/bin/bash
################################################################################
# File for processing results of GFDL model runs AS THEY ARE PRODUCED; use this
# in parallel after every model step while next model step is simultaneously running.
# ---------
# Summary of current variables:
# * with longitude-data:
#   p, t, u, v, z, vor, omega, teq, D, pt, pv s
#   forget dthdp (only will want lapse rate to diagnose mean climate/tropopause
#   heights and can use the mean t/theta fields), but keep S; has physical interpretation
# * without longitude-data:
#   t, u, v, z, vor, omega, teq, D, dthdp, pt, pv, s, **NEW** EHF, EMF, EPF, EKE, C, KE
# Tips:
# Run 'grep -r -l "^[^\!].*register_diag_field(" . | grep ".*\.f90"' at base of source
# directory to see list of files where diag_fields are registered.
################################################################################
# Function for checking NCL scripts success
# Script sometimes fails to spawn child process for displaying time information; ignore these errors
# Also Execute.c is always shown as error alongside specific function error, so ignore that one
nclcheck() { # input log file as argument
  cat $1 | grep -v "Execute.c" | grep -v "systemfunc" | egrep "^fatal:" &>/dev/null
  return $? # return exit code; good status means we found error, bad status means we found nothing
    # ignore ^warning: because these will also happen if we have a systemfunc error possibly
}

# Parse input flags
# cores=8 # default cores for mppnccombine, actually this didn't work so nevermind
_dir='.'
_debug=false   # keep data in original folder, instead of moving to ../netcdf? useful for testing
_resume=false  # process old "full" files?
_keepxyz=false # keep original "full" results?
_combine=false # only combine model files, nothing else?
while [ $# -gt 0 ]; do
  case $1 in
    -c|--combine) echo "Only combining files." && _combine=true ;;
    -q|--quit) echo "Skipping processing." && exit 0 ;;
    -d=*|--dir=*)  _dir=${1##*=} ;;
    -d|--debug)  _debug=true   ;;  # if true, keep all intermediate files
    -r|--resume) _resume=true  ;; # process old results sitting in the directory
    -k|--keep)   _keepxyz=true ;; # whether to keep longitudinal data
    *) echo "Error: Unknown flag \"$1\"." && exit 127 ;;
  esac
  shift # shift by one
done
$_debug && _keepxyz=true
$_resume && _keepxyz=true # we are *reading* from existing XYZ files so definitely don't delete them!

# Global vars
t0=$(date +%s) # starting time
bin=$(readlink -f ${0%/*})  # same location as this file; trim filename from right
run=mpirun # for running mppnccombine on Cheyenne; parallelization really necessary
interp_cdo=$bin/process_interp.cdo # interpolate with CDO
interp_ncl=$bin/process_interp.ncl # interpolate with NCL, automatic iteration
mppnccombine=$bin/mppnccombine.x # combine; needs to have been compiled here
process=$bin/process_params.ncl  # eddy and mean Lorenz energy cycle terms with NCL
means=$bin/process_means.ncl     # just gets zonal means
cd $_dir # optionally pass dir argument

# Double check some stuff
[ ! -r $process ]        && echo "Error: The script \"$process\" is missing."                       && exit 127
[ ! -r $interp_ncl ]     && echo "Error: The script \"$interp_ncl\" is missing."                    && exit 127
[ ! -x $mppnccombine ]  && echo "Error: The mpp combine executable \"$mppnccombine\" is missing." && exit 127
! hash ncl 2>/dev/null  && echo "Error: NCL is not in $PATH."                                     && exit 127
! hash cdo 2>/dev/null  && echo "Error: CDO is not in $PATH."                                     && exit 127
! hash ncks 2>/dev/null && echo "Error: NCO is not in $PATH."                                     && exit 127

################################################################################
# Functions
# Stdout of following lines is overview; view separate logfiles for specifics
################################################################################
# Function for interpolating model levels
hybrid_to_press() {
  # Interplolate to pressure levels from model levels
  local t log filename output suffix
  filename="$1"
  suffix="$2"
  output=${filename%%.*}_interp.$suffix
  log=LOGS/log.interp.${suffix%.nc}
  t=$(date +%s)

  # Apply some simple modifications to attributes
  ncrename -d pfull,mlev $filename &>/dev/null # mlev is the ECHAM convention, needed for CDO interpolation
  ncrename -d phalf,ilev $filename &>/dev/null # ilev is the other ECHAM convention
  ncrename -v pfull,mlev $filename &>/dev/null # -d renames dimensions, -v renames variables of same name
  ncrename -v phalf,ilev $filename &>/dev/null
  ncatted -O -a bounds,mlev,o,c,"ilev" $filename

  # Interpolation
  echo "Interpolating with NCL..." # -Q = no banner, -n = do not enumerate print statements
  [ -r "$output" ] && rm "$output"
  ncl -n -Q "filename=\"$filename\"" "output=\"$output\"" $interp_ncl &>$log #2> /dev/null
  if nclcheck $log || [ ! -r $output ]; then
    echo "Error: Something failed during NCL interpolation." && exit 2
  fi

  # Standardize attributes
  # Many of these may already be properly set, but make sure; CDO also may want
  # a few special ones like 'axis' and 'standard_name'
  # NOTE: This is really fast (0.02s on T42 20 day file)
  # This is much faster than even editing one attribute in NCL (0.05s)
  ncatted -O -a NumFilesInSet,global,o,l,$numfiles \
    -a edges,lon,d,, -a edges,lat,d,, \
    -a axis,lon,o,c,"X" -a axis,lat,o,c,"Y" -a axis,plev,o,c,"Z" -a axis,time,o,c,"T" \
    -a long_name,plev,o,c,"pressure_level" -a units,plev,o,c,"mb" -a bounds,plev,o,c,"plev_bnds" \
    -a long_name,lat,o,c,"latitude"  -a standard_name,lat,o,c,"latitude" \
    -a long_name,lon,o,c,"longitude" -a standard_name,lon,o,c,"longitude" \
    -a standard_name,time,o,c,"time" \
    -a units,lat,o,c,"degrees_north" -a units,lon,o,c,"degrees_east" $output
  ! $_debug && mv $output $filename # move old file on top of new file
  echo "  * Time for interpolation: $(($(date +%s) - t))s."
}

# Means
means() {
  # Get the zonal means
  local t log filename output suffix
  filename="$1"
  suffix="$2"
  output=means.${suffix}
  log=LOGS/log.means.${suffix%.nc}
  t=$(date +%s)
  echo "Getting zonal means..."
  [ -r "$output" ] && rm "$output"
  ncl -n -Q "filename=\"$filename\"" "output=\"$output\"" $means &>$log
  if nclcheck $log; then
    echo "Error: Something failed while getting zonal means." && exit 4
  fi
  echo "  * Time for getting zonal means: $(($(date +%s) - t))s."
}

# Once, this function also accepted averaged data; not anymore, but these are
# some approaches for testing if file has averaged data
params() {
  # Ouput file names
  local t log filename output suffix
  filename="$1"
  suffix="$2"
  output=params.${suffix}
  log=LOGS/log.params.${suffix%.nc}
  t=$(date +%s)
  echo "Getting other params..."
  [ -r "$output" ] && rm "$output"
  ncl -n -Q "filename=\"$filename\"" "output=\"$output\"" "suffix=\"$suffix\"" $process &>$log
  if nclcheck $log; then
    echo "Error: Something failed while getting other params." && exit 4
  fi
  echo "  * Time for getting other params: $(($(date +%s) - t))s."
}

################################################################################
# Driver, calls above functions
################################################################################
# Get files
if $_debug; then
  _parallel=true
  files=(test.nc.0000) # doesn't really exist
elif $_resume; then
  _parallel=false
  files=(*_full.${PWD##*/}.nc) # the preserved output file
else
  _parallel=true
  files=(*.nc.0000)
fi
if [[ "$files" =~ "*" ]]; then
  files=(*.nc) # already present?
  [ ${#files[@]} -eq 1 ] && echo "Error: XYZ resolution files not found." && exit 1 # make sure nullglob turned off
  echo "Note: Model ran on only 1 core, do not need to merge files."
fi
# Loop through each file
for file in ${files[@]}; do
  ##############################################################################
  # Initial stuff
  ##############################################################################
  # File names and such
  base=${file%%.*}
  if $_debug && $_resume; then
    parts=(${base}.*.nc) # check if already present
  elif $_resume; then
    parts=(${file})
  else
    for part in ${base}.nc*; do
      num=${part##*.}
      mv $part ${base}.${num}.nc & # some programs won't recognize file without .nc extension
    done
    wait # in background
    parts=(${base}.*.nc)
  fi
  echo Files: ${parts[@]}
  numfiles=${#parts[@]}
  xyzfile="${base}_full.${PWD##*/}.nc"   # original data
  yzfile="${base}_summary.${PWD##*/}.nc" # longitude-averaged data
  # Just want to combine files and exit?
  if $_combine; then
    [ -r ${base}.nc ] && rm ${base}.nc
    $mppnccombine -r ${base}.nc  ${parts[@]}
    continue
  fi

  ##############################################################################
  # 1) Interpolate to pressure, get means in parallel
  ##############################################################################
  tp=$(date +%s)
  echo "Interpolating and getting means..."
  ! [ -d LOGS ] && mkdir LOGS
  for ncfile in ${parts[@]}; do
    if ! $_debug && $_resume; then
      # Just get means
      num=0000
      suffix=nc # dummy value
      means "$ncfile" "nc" &>LOGS/log.$num &
    else
      # Number
      num=${ncfile%.nc}
      num=${num#*.}
      suffix=${num}.nc
      # Interpolate and get means
      $_debug && mfile=${ncfile%%.*}_interp.$suffix || mfile=$ncfile
      { hybrid_to_press "$ncfile" "$suffix"; means "$mfile" "$suffix"; } &>LOGS/log.$num &
    fi
  done
  wait
  $_debug && parts=(${base}_interp.*.nc) # we didn't overwrite them
  echo "  * Time for interpolating and getting zonal means in parallel: $(($(date +%s) - tp))s."
  # Merge the files
  # NOTE: Use mppnccombine -h to print help info; the -r removes files after
  # run was successful
  if $_parallel; then
    echo "Combining zonal mean files..."
    t=$(date +%s)
    [ -r means.nc ] && rm means.nc
    $mppnccombine means.nc means.*.nc
    echo "  * Time for combining zonal mean files: $(($(date +%s) - t))s."
  fi

  ##############################################################################
  # 2) Calculate other params in parallel
  ##############################################################################
  # Global means were required for some, hence the initial merge
  tp=$(date +%s)
  echo "Getting other params..."
  for ncfile in ${parts[@]}; do
    # Number
    if $_resume && ! $_debug; then
      num=0000
      suffix=nc # dummy value
    else
      num=${ncfile%.nc}
      num=${num#*.}
      suffix=${num}.nc
    fi
    params "$ncfile" "$suffix" &>>LOGS/log.${num} &
  done
  wait
  echo "  * Time for getting params in parallel: $(($(date +%s) - tp))s."
  # Merge the files
  if $_parallel; then
    echo "Combining param files..."
    t=$(date +%s)
    [ -r params.nc ] && rm params.nc
    $mppnccombine params.nc params.*.nc
    echo "  * Time for combining param files: $(($(date +%s) - t))s."
  fi
  # Append means to file
  ncks -A means.nc params.nc
  $_debug && _cmd=cp || _cmd=mv
  $_cmd params.nc $yzfile
  # Cleanup
  ! $_debug && rm means.nc means.*.nc params.*.nc

  ##############################################################################
  # 3) Optionally merge the pressure-interpolated files
  ##############################################################################
  # TODO: Consider reducing to a standard horizontal resolution at least, if
  # not vertical? This could save considerable space.
  if ! $_keepxyz; then
    # Delete the old file
    echo "Removing XYZ files..."
    ! $_debug && rm ${parts[@]} # simple
  elif ! $_resume || $_debug; then
    # Merge files
    # Will drop variables in parallel before merging
    t=$(date +%s)
    echo "Keeping XYZ files..."
    for ncfile in ${parts[@]}; do
      # ncks -O -d time,1,,2 -x -v omega,udt,vdt,tdt $ncfile $ncfile &
      $_debug && out=${ncfile%%.*}_x.${ncfile#*.} || out=$ncfile
      ncks -O -x -v omega,udt,vdt,tdt $ncfile $out &
      interp+=($out)
    done
    wait
    [ -r $xyzfile ] && rm $xyzfile
    $mppnccombine -r $xyzfile ${interp[@]}
    echo "  * Time for combining XYZ files: $(($(date +%s) - t))s."
  fi

  ##############################################################################
  # Then copy files to common directory
  ##############################################################################
  if ! $_debug; then
    ! [ -d ../netcdf ] && mkdir ../netcdf
    [ -r $yzfile ]  && mv $yzfile ../netcdf
    [ -r $xyzfile ] && mv $xyzfile ../netcdf
  fi
done

# Echo time of finish
# Can parse this to send message to the window that ran the runscript/batch runscript
# echo $(($(date +%s) - $t0)) # prints UNIX time difference
echo "TOTAL TIME ELAPSED: $(($(date +%s) - t0))s."
