#!/usr/bin/env bash
usage="process_init"
doc="This script is used to process the initial 1-second model run used
for generating a NetCDF file of constants.

Usage

    $usage

Optional arguments

  -h|--help     Print this message and quit.
"
# Initial stuff
shopt -s nullglob
source ${0%/*}/header.sh
t0=$(date +%s) # starting time
files=(*.nc)
[ ${#files[@]} -eq 0 ] && raise 1 "Found no NetCDF files in directory $(pwd)."
[ ${#files[@]} -gt 1 ] && raise 1 "Expected 1 NetCDF file in directory $(pwd), found ${#files[@]}: ${files[*]}."
file=${files[0]}
ncrename -h -d pfull,mlev $file
ncrename -h -d phalf,ilev $file
ncrename -h -v pfull,mlev $file
ncrename -h -v phalf,ilev $file
ncatted -h -O -a bounds,mlev,o,c,"ilev" $file

# Interpolate and move $file to top-level of directory
# WARNING: cdo -O -zonmean -timmean file.nc file.nc silently sets all data to zero
log=interp.log
interp=${0%/*}/pressure_interp.ncl  # interpolate with NCL, automatic iteration
ncl -n -Q 'filename="'$file'"' 'output="tmp.nc"' $interp &>$log
sed -i '/^.*warning:.*$/d;/^$/d' $log
ncltest $log && [ -r $file ] || raise 1 'Something failed during NCL interpolation of constants.'
cdo -O -zonmean -timmean tmp.nc ../$file || raise 1 'Something failed during CDO averaging.'
rm tmp.nc $file 2>/dev/null
echo "TOTAL ELAPSED TIME: $(($(date +%s) - t0))s."
