#!/bin/bash
ncfile=$1
flags="-s -O"
g=9.80 # gravity
R=287.04 # dry gas constant
cp=1004.64 # R divided by kappa (2/7)
function wrapup() { # if file not found CDO operation failed
  # segregate the Lorenz grid from zonal-mean grids by renaming
  # from lat/lon to dummy singleton dimensions y/x
  [ ! -r $1 ] && echo "ERROR: File $1 not found." && exit 1
  ncrename -O -d lon,x -d lat,y $1 $1 # renames the singleton dimensions
  ncatted -O -a units,x,d,, \
    -a standard_name,x,d,, \
    -a long_name,x,o,c,"X" \
    -a units,y,d,, \
    -a standard_name,y,d,, \
    -a long_name,y,o,c,"Y" $1
}

################################################################################
# Gets the terms G (generation), APE (total sum), C (conversion), TKE (total energy), 
# and D (dissipation); equation for the last one can be found in hs_forcing.90 source code
t=$(date +%s)
torig=$t
echo "Getting Lorenz cycle parameters with CDO..."
out=lorenz1.nc
cdo $flags -setattribute,G@long_name="APE generation",G@units="W/m2 Pa" \
    -setname,G -mulc,$R -divc,$g \
      -div -sub -fldmean -mul -selname,ndamp $ncfile -selname,t $ncfile \
                -mul -fldmean -selname,ndamp $ncfile -fldmean -selname,t $ncfile \
           -fldmean -selname,s $ncfile \
      $out
ncap2 -O -s "G=G/(100.*plev)" $out $out
wrapup $out
echo "  * Time for APE generation: $(($(date +%s) - $t))s."
t=$(date +%s)
out=lorenz2.nc
cdo $flags -setattribute,APE@long_name="available potential energy",APE@units="J/m2 Pa" \
    -setname,APE -mulc,0.5 -mulc,$R -divc,$g \
      -div -sub -fldmean -sqr -selname,t $ncfile \
                -sqr -fldmean -selname,t $ncfile \
           -fldmean -selname,s $ncfile \
      $out &&
ncap2 -O -s "APE=APE/(100.*plev)" $out $out
wrapup $out
echo "  * Time for APE: $(($(date +%s) - $t))s."
t=$(date +%s)
out=lorenz3.nc
cdo $flags -setattribute,C@long_name="APE conversion to KE",C@units="W/m2 Pa" \
    -setname,C -mulc,$R -divc,$g \
      -sub -fldmean -mul -selname,omega $ncfile -selname,t $ncfile \
           -mul -fldmean -selname,omega $ncfile -fldmean -selname,t $ncfile \
      $out
ncap2 -O -s "C=C/(100.*plev)" $out $out
wrapup $out
echo "  * Time for APE conversion: $(($(date +%s) - $t))s."
t=$(date +%s)
out=lorenz4.nc
cdo $flags -setattribute,TKE@long_name="kinetic energy",TKE@units="J/m2 Pa" \
    -setname,TKE -mulc,0.5 -divc,$g \
      -fldmean -add -sqr -selname,u $ncfile -sqr -selname,v $ncfile \
      $out; wrapup $out
echo "  * Time for kinetic energy: $(($(date +%s) - $t))s."
t=$(date +%s)
out=lorenz5.nc
cdo $flags -setattribute,D@long_name="KE dissipation",D@units="W/m2 Pa" \
    -setname,D -mulc,$cp -divc,$g \
      -fldmean -selname,rdamp $ncfile \
      $out; wrapup $out
echo "  * Time for kinetic energy dissipation: $(($(date +%s) - $t))s."
echo "TOTAL TIME ELAPSED: $(($(date +%s) - $torig))s."
