#!/usr/bin/env bash
# Rename all experiments
# following new conventions
shopt -s nullglob
roots=(/mdata1/ldavis /mdata2/ldavis ~/data)
for root in ${roots[@]}; do
  subs=($root/. $root/timescales*)
  for sub in ${subs[@]}; do
    for forcing in hs pk dbt; do
      for experiment in $sub/${forcing}_*; do
        # Info
        old=$experiment
        case $experiment in
          *diag*)
            blopt=${experiment#*diag}
            blopt=${blopt%%_*}
            experiment=${experiment/diag?/katmos${blopt}-kfric}
            ;;
          *fixedmean*)
            experiment=${experiment/fixedmean/fixed}
            ;;
          *_fric*)
            experiment=${experiment/fric/kfric}
            ;;
          *troprad*)
            experiment=${experiment/troprad/katmos}
            ;;
          *stratrad*)
            prefix=${experiment%stratrad*}
            suffix=${experiment#*stratrad}
            spec=${suffix%%_*}
            suffix=${suffix#*_} # resolution and parameters
            mode=$(echo ${spec##*[0-9]} | tr c 0 | tr l 1)
            depth=$(printf "%08.3f" ${spec%[lc]})
            experiment=${prefix}kstrat${mode}_${suffix}p${depth}
            ;;
          *)
            # echo "Warning: Unknown experiment pattern \"${experiment}\"."
            continue
            ;;
        esac
        # Rename
        echo ${old##*/} to ${experiment##*/}
        mv $old $experiment
      done
    done
  done
done
