#!/usr/bin/env bash
################################################################################
# This file is used to generate various experiment series with 'run_sweep'
# TODO: Get spectral decompositions for control runs.
################################################################################
cd ${0%/*} || exit 1

# Test run
# ./run_sweep --test --testblocks=2 --testdays=1 hs1_base_t42l20s
# ./run_sweep --test --testblocks=2 --testdays=1 hs1_base_t85l60e
# exit 0

# Test runs that just deliver forcing data
# for force in pkmod pk hs; do
#   ./run_sweep -i ${force}1_base_t95l60p
# done
# exit 0

# Main runs
if [[ $HOSTNAME =~ monde ]]; then
  # Long climatology for Jingyuan
  # ./run_sweep -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=9500 -kts=500 -kte=9500 \
  #   --1=40 hs1_ntau_t42l20s

  # Basic experiments and locked runs
  # for blopt in 1 2; do
  # for fopts in c l; do
  # for reso in t42l20s t85l60e
  for reso in t85l60e; do
    for blopt in 1; do
      # Configure flags
      # Save mean tdt from each run because takes up very little space
      # flags='-r -s -d=100 -dt=1200 -c=8 -ts=0 -te=5500 -kts=500'
      # [ -z "$fopts" ] && flags+=' -rt' || flags+=' -rs'
      flags='-r -c=16 -d=20 -ds=500 -dt=600 -kte=0 -fw=12 -f=2xdaily_inst'
      fflags=${flags/600/400}  # sligjtly faster for certain experiments

      # Forcing experiments
      # TODO: Delete doubled CO2 experiments
      # for force in '0.5 qtropical' '0.08 qrealistic' '0.06 qglobal'; do
      for force in '0.08 qrealistic'; do
        for tend in 5500; do
          # for param in 10 20 40 100 60 80 30 50; do  # extend control and response at same time
          f=${force#* }
          q=${force% *}
          ./run_sweep $flags --tend=$tend \
            --ntau=120,160,200 --${f}=0,0:${q} hs${blopt} ${reso} || exit 1
        done
      done

      # Standard experiment series
      # NOTE: Locked runs always continue from the end of the
      # run they are using for heating data. Otherwise get instability.
      for tend in 5500; do
        ./run_sweep $flags --tend=$tend \
          --ntau=40,20,10,100,100:200,200:400,4,2,1,0.4 hs${blopt} ${reso}
      done
      for tend in 5500; do
        ./run_sweep $flags --tend=$tend \
          --tgrad=60:40,40:20,20:10,90,120 hs${blopt} ${reso}
        ./run_sweep $fflags --tend=$tend \
          --tgrad=150,180 hs${blopt} ${reso}
      done
    done
  done

  # Finish incomplete 5500 day integrations
  # TODO: Run this (2020-10-24)!
  # flags='-r -c=16 -d=100 -dt=1200 -kte=0 -fw=12 -f=2xdaily_inst'
  # for blopt in 1 2; do
  #   ./run_sweep $flags \
  #     --ntau=60 \
  #     --tend=5500 \
  #     hs${blopt}_ntau_t42l20s
  #   ./run_sweep $flags \
  #     --ntau=40,10,100,20,60 --2=0,300:310 \
  #     --tend=5500 \
  #     hs${blopt}_ntau-tmean_t42l20s
  # done

  # Gradient shift experiments for different absolute equilibrium
  # temp differences
  # TODO: Delete these?
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=5500 -kts=500 -kte=5500 --1=-2,2 \
  #   hs_tshift_t42l20s
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=5500 -kts=500 -kte=5500 \
  #   --1=20,60,100,140 --2=-2,2 \
  #   hs_tgrad-tshift_t42l20s
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=5500 -kts=500 -kte=5500 \
  #   --1=40,80,120,160 --2=-2,2 \
  #   hs_tgrad-tshift_t42l20s

  # Integrate all long-timescale experiments an extra 5000 days
  # TODO: Not done yet?
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs1_ntaumean_t42l20s
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs1_ntau_t42l20s
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs2_ntaumean_t42l20s
  # ./run_sweep --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs2_ntau_t42l20s

elif [[ $HOSTNAME =~ cheyenne ]]; then
  # Test
  # ./run_sweep -c=36 -dt=400 \
  #   --test -td=1 -tb=5 -tn=test-process \
  #   hs1_ntau_t95l60e --1=40

  # For supercomputer
  flags='-r -n=1 -c=36 -d=20 -fw=12 -f=2xdaily_inst -te=3500 -kts=500'
  ./run_sweep $flags -dt=400 --ntau=1,2,4,10 hs1 t95l60e
  ./run_sweep $flags -dt=600 --ntau=20 hs1 t95l60e
  ./run_sweep $flags -dt=800 --ntau=40:100 hs1 t95l60e
  ./run_sweep $flags -dt=1000 --ntau=40:200,40:400 hs1 t95l60e
  ./run_sweep $flags -dt=1200 --ntau=40:1000 hs1 t95l60e

  # Stratosphere experiments. Also change damping throughout *entire atmosphere*
  # for point of comparison. Should be neat.
  # # Polvani Kushner setup
  # ./run_sweep --resume -dt=800 \
  #   -c=36 -n=1 -d=20 -ts=0 \
  #   -te=3500 -kts=500 -kte=5500 --1=1,2,4,10,20,40 --2=3 \
  #   pk_kstrat0_t95l60e
  # ./run_sweep --resume -dt=800 \
  #   -c=36 -n=1 -d=20 -ts=0 \
  #   -te=3500 -kts=500 -kte=5500 --1=1,2,4,10,20,40 --2=3 \
  #   pk_ntau_t95l60e
fi
