#!/usr/bin/env bash
################################################################################
# This file is used to generate various experiment series with 'run_series'
# TODO: Get spectral decompositions for control runs.
################################################################################
cd ${0%/*} || exit 1

# Test run
# ./run_series -s -t -tb=2 -td=10 hs1_base_t42l20s
# exit 0

# Test runs that just deliver forcing data
# for force in pkmod pk hs; do
#   ./run_series -i ${force}1_base_t95l60p
# done
# exit 0

# Main runs
if [[ ${HOSTNAME} =~ monde ]]; then
  # For Jingyuan; long climatology
  # ./run_series -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=9500 -kts=500 -kte=9500 \
  #   --1=40 hs1_tdamp_t42l20s

  # Basic experiments and locked runs
  for blopt in 1 2; do
    # for fopts in c l; do
    for fopts in ''; do
      # Configure flags
      # Save mean tdt from each run because takes up very little space
      flags='-r -s -d=100 -dt=1200 -c=8 -ts=0 -te=5500 -kts=500 -kte=5500'
      # if [ -z "$fopts" ]; then
      #   flags+=' -rt'  # re-run just to get the mean_tdt.nc files?
      # else
      #   flags+=' -rs'  # exit if experiment ran successfully to tend, i.e. repair crashes
      # fi

      # Base experiment
      ./run_series $flags \
        --1=40 hs${blopt}${fopts}_tdamp_t42l20s

      # Standard experiment series
      # NOTE: Locked runs always continue from the end of the
      # run they are using for heating data. Otherwise get instability.
      ./run_series $flags \
        --1=20,10,4,2,1,0.4,0.2,40:100,100:200,200:400,400:1000 hs${blopt}${fopts}_tdamp_t42l20s
      ./run_series $flags \
        --1=20,10,4,40:100,100:200,200:400,400:1000 hs${blopt}${fopts}_tdampmean_t42l20s
      ./run_series $flags \
        --1=60:40,40:20,20:10,10:4,90,120,150,200 hs${blopt}${fopts}_tgrad_t42l20s
      ./run_series $flags \
        --1=280,290,310,320 hs${blopt}${fopts}_tmean_t42l20s

      # Forcing experiments
      for force in \
        '0.5 tropical' '0.08 realistic' '0.06 global' \
        # '0.03 global' '0.04 realistic'
        do
        q=${force% *}
        f=${force#* }
        ./run_series $flags \
          --1=40,20,60,10,100 --2=0:${q} \
          hs${blopt}${fopts}_tdamp-${f}_t42l20s
      done
    done
  done

  # Diagonal experiments
  # WARNING: For default damping rate, continuation experiments not
  # necessary for tgrad and tmean experiments.
  # for blopt in 1 2; do
  #   for k in 40 20 60 10 100; do
  #   # for k in 40 20 60 4 400; do
  #     dt=1200
  #     [ $k -eq 40 ] && continue
  #     # Global warming
  #     ./run_series -r -dt=$dt -c=8 -d=100 -ts=0 \
  #       -te=$te -kts=500 -kte=3500 \
  #       --1=$k --2=300:280,300:290,300:310,300:320 hs${blopt}_tdamp-tmean_t42l20s
  #     # Temperature gradient
  #     ./run_series -r -dt=$dt -c=8 -d=100 -ts=0 \
  #       -te=$te -kts=500 -kte=3500 \
  #       --1=$k --2=60:40,60:90,60:120,60:150,60:20 hs${blopt}_tdamp-tgrad_t42l20s
  #   done
  # done

  # Gradient shift experiments for different absolute equilibrium
  # temp differences
  # TODO: Delete these?
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=5500 -kts=500 -kte=5500 --1=-2,2 \
  #   hs_tshift_t42l20s
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=5500 -kts=500 -kte=5500 \
  #   --1=20,60,100,140 --2=-2,2 \
  #   hs_tgrad-tshift_t42l20s
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=0 \
  #   -te=5500 -kts=500 -kte=5500 \
  #   --1=40,80,120,160 --2=-2,2 \
  #   hs_tgrad-tshift_t42l20s

  # Integrate all long-timescale experiments an extra 5000 days
  # TODO: Not done yet?
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs1_tdampmean_t42l20s
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs1_tdamp_t42l20s
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs2_tdampmean_t42l20s
  # ./run_series --resume -dt=1200 -c=8 -d=100 -ts=5500 \
  #   -te=9900 -kts=500 -kte=5500 \
  #   --1=40:100,100:200,200:400,400:1000 hs2_tdamp_t42l20s

elif [[ $HOSTNAME =~ cheyenne ]]; then
  # Test
  # ./run_series -c=36 -dt=400 \
  #   --test -td=1 -tb=5 -tn=test-process \
  #   hs1_tdamp_t95l60e --1=40

  # For supercomputer
  # NOTE: We really try to tune the model step for this one!
  # NOTE: Already have base experiment finished
  # NOTE: Try just 3000 day integration for now.
  # Basic ones
  ./run_series --resume -dt=400 \
    -c=36 -n=1 -d=20 -ts=0 \
    -te=3500 -kts=500 -kte=5500 --1=1,2,4,10 \
    hs1_tdamp_t95l60e
  ./run_series --resume -dt=600 \
    -c=36 -n=1 -d=20 -ts=0 \
    -te=3500 -kts=500 -kte=5500 --1=20 \
    hs1_tdamp_t95l60e

  # Continuation runs (wait until others have finished)
  ./run_series --resume -dt=800 \
    -c=36 -d=20 -ts=0 \
    -te=3500 -kts=500 -kte=5500 --1=40:100 \
    hs1_tdamp_t95l60e
  ./run_series --resume -dt=1000 \
    -c=36 -d=20 -ts=0 \
    -te=3500 -kts=500 -kte=5500 --1=40:200,40:400 \
    hs1_tdamp_t95l60e
  ./run_series --resume -dt=1200 \
    -c=36 -d=20 -ts=0 \
    -te=3500 -kts=500 -kte=5500 --1=40:1000 \
    hs1_tdamp_t95l60e

  # Stratosphere experiments
  # Also change damping throughout *entire atmosphere* for point
  # of comparison. Should be neat.
  # # Polvani Kushner setup
  # ./run_series --resume -dt=800 \
  #   -c=36 -n=1 -d=20 -ts=0 \
  #   -te=3500 -kts=500 -kte=5500 --1=1,2,4,10,20,40 --2=3 \
  #   pk_kstrat0_t95l60e
  # ./run_series --resume -dt=800 \
  #   -c=36 -n=1 -d=20 -ts=0 \
  #   -te=3500 -kts=500 -kte=5500 --1=1,2,4,10,20,40 --2=3 \
  #   pk_tdamp_t95l60e
  # # Custom setup
  # ./run_series --resume -dt=800 \
  #   -c=36 -n=1 -d=20 -ts=0 \
  #   -te=3500 -kts=500 -kte=5500 --1=1,2,4,10,20,40 --2=3 \
  #   pk_kstrat0_t95l60e
  # ./run_series --resume -dt=800 \
  #   -c=36 -n=1 -d=20 -ts=0 \
  #   -te=3500 -kts=500 -kte=5500 --1=1,2,4,10,20,40 --2=3 \
  #   pk_tdamp_t95l60e
fi
