#!/usr/bin/env bash
#-----------------------------------------------------------------------------#
# List the variables in the NetCDF files stored in every single
# experiment directory.
#-----------------------------------------------------------------------------#
shopt -s nullglob
names=("$@") # remember $@ is special, nothing gets expanded
roots=(~/scratch*)  # symlinks to scratch
[ -z "$1" ] && names=("hs[12]_*")

# Relevant naemlist parameters
nmlvalues() {
  cat "$1" | grep -E 'ktrop|kbl|delh'  | xargs
}

# Netcdf tools
nclist() {
  command ncdump -h "$1" | sed -n '/variables:/,$p' | sed '/^$/q' | grep -v '[:=]' \
    | cut -d';' -f1 | cut -d'(' -f1 | sed 's/ *$//g;s/.* //g' | xargs | tr ' ' '\n' | grep -v '[{}]' | xargs
}
ncdimlist() {
  command ncdump -h "$1" | sed -n '/dimensions:/,$p' | sed '/variables:/q' \
    | cut -d'=' -f1 -s | xargs | tr ' ' '\n' | grep -v '[{}]' | xargs
}
ncvarlist() {
  local list dmnlist varlist
  list=($(nclist "$1"))
  dmnlist=($(ncdimlist "$1"))
  for item in "${list[@]}"; do
    # shellcheck disable=2076
    if [[ ! " ${dmnlist[*]} " =~ " $item " ]]; then
      varlist+=("$item")
    fi
  done
  echo "${varlist[@]}" | tr -s ' ' '\n' | grep -v '[{}]' | sort | xargs | sed 's/plev_bnds //'
}

# Iterate
echo
cwd=$(pwd)
prefix=2xdaily_inst
log=$cwd/${0%_log}.log
series=''
rm $log 2>/dev/null
for root in ${roots[@]}; do
  echo "Root: $root" | tee -a $log
  unset globs
  for name in "${names[@]}"; do
    globs+=($root/$name) # performs expansion
  done
  [ ${#globs[@]} -eq 0 ] && echo "No $name files found in ${root}." && continue
  for path in ${globs[@]}; do
    # Get params corresponding to that parameter series, so we can echo them
    dir=${path##*/}
    nfields=$(echo $dir | tr '^_' ' ' | wc -w)
    iseries=${dir%_p*}
    [ "$iseries" != "$series" ] && {
      echo
      echo "Series: $iseries"
      echo
    } | tee -a $log
    series=$iseries
    if [ $nfields -eq 3 ]; then
      params="default"
    else
      params=${dir##*_}
      params="$(echo $params | tr p ' ' | sed 's/ 0*/ /g' | sed 's/ \./ 0./g' | xargs | sed 's/ /, /g')"
    fi
    echo $params | tee -a $log # parameters

    # Loop through days
    unset day1 day2 vars1 vars2 params1 params2
    pday1=0000
    vday1=0000
    ddirs=($path/d????-d????)
    ndays=${#ddirs[@]}
    for i in $(seq 1 $ndays); do
      # Get summary file and namelist file
      ddir=${ddirs[i-1]}
      days=${ddir##*/}
      ncfile=$path/netcdf/${prefix}_summary.${days}.nc
      nmlfile=$ddir/input.nml
      day2=${days##*d}
      # day2=${days#d}
      # day2=${day2%-*}

      # Print namelist parameters, if changed
      if [ -r $nmlfile ]; then
        params2=$(nmlvalues $nmlfile)
        if [ -n "$params1" ] && [ "$params1" != "$params2" ]; then
          echo "  d${pday1}-d${day2}: $params1" | tee -a $log
          pday1=$day2
        fi
        params1=$params2
      fi

      # Print variable list, if changed
      if [ -r $ncfile ]; then
        vars2=$(ncvarlist $ncfile)
        if [ -n "$vars1" ] && [ "$vars1" != "$vars2" ]; then
          echo "  d${vday1}-d${day2}: $vars1" | tee -a $log
          vday1=$day2
        fi
        vars1=$vars2
      fi
    done

    # Print *final* information
    echo "  d${pday1}-d${day2}: $params1" | tee -a $log
    echo "  d${vday1}-d${day2}: $vars1" | tee -a $log
  done
  echo | tee -a $log
done
