#!/usr/bin/env bash
shopt -s nullglob
#------------------------------------------------------------------------------#
# Show files currently available
#------------------------------------------------------------------------------#
log=${0%_log}.log
root=~/data/timescales
prefix=2xdaily_inst_
rm $log 2>/dev/null
globs=("$@")
[ "${#globs[@]}" -eq 0 ] && globs=("*t42l20s*")
for glob in "${globs[@]}"; do
  for folder in $root/$glob; do
    # Get params corresponding to that parameter series
    dir=${folder##*/}
    nfields=$(echo $dir | tr '[^_]' ' ' | wc -w)
    iseries=${dir%_p*}
    if [ "$iseries" != "$series" ]; then
      echo "Series: $iseries"
      printf "\nSeries: $iseries\n" &>> $log # new line
    fi
    series=$iseries
    if [ $nfields -eq 3 ]; then
      params="default"
    else
      params=${dir##*_}
      params="$(echo $params | tr p ' ' | sed 's/ 0*/ /g' | sed 's/ \./ 0./g' | xargs | sed 's/ /, /g')"
    fi
    echo $params &>> $log # parameters

    # Print if file available
    unset message
    for suffix in \
        constants \
        autocorr \
        climate climate_isen \
        spectral spectral_phase \
        eofs_nh eofs_nh_vert \
        energy; do
    # for file in autocorr; do
      if [ $suffix == constants ]; then
        ncfiles=($folder/${suffix}.nc*)
      else
        ncfiles=($folder/${prefix}${suffix}.*.nc)
      fi
      for ncfile in ${ncfiles[@]}; do
        name=${ncfile%.nc}
        name=${ncfile##*/}
        message+="$name $(du -h "$ncfile" | awk '{print $1}') $(date -u -r $ncfile)\n"
      done
    done
    printf "$message" | column -t -o' ' | awk '{print "    "$0}' &>> $log
  done
done
